version: '3.8'

networks:
  app-tier:
    driver: bridge

services:

  wordpress:
    image: bitnami/wordpress:latest
    expose:
      - PING_LISTEN_PORT
    deploy:
      replicas: 2
    restart: always
    environment:
      - PING_LISTEN_PORT=3000
      - WORDPRESS_DATABASE_HOST=database
      - WORDPRESS_DATABASE_USER=wordpress
      - WORDPRESS_DATABASE_PASSWORD=wordpress
      - WORDPRESS_DATABASE_NAME=wordpress
    networks:
      - app-tier

  database:
    image: bitnami/mysql:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
      - MYSQL_DATABASE=wordpress
    depends_on:
      - wordpress
    networks:
      - app-tier


  cache:
    image: bitnami/redis:latest
    restart: always
    depends_on:
      - wordpress
      - database
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-tier


  proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    environment:
      - PING_LISTEN_PORT=3000
    ports:
      - 8081:80
    depends_on: 
      - wordpress
    networks:
      - app-tier

