version: '3.8'

networks:
  app-tier:
    driver: bridge

services:

  wordpress:

    image: bitnami/wordpress:latest

    build:
      context: .
      dockerfile: Dockerfile

    expose:
      - PING_LISTEN_PORT

    deploy:
      replicas: 2
    
    restart: always

    environment:
      - PING_LISTEN_PORT=3000
    
    networks:
      - app-tier

  database:

    image: bitnami/mysql:latest

    restart: always

    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    
    depends_on:
      - wordpress

    networks:
      - app-tier


  cache:

    image: bitnami/redis:latest

    restart: always
    
    depends_on:
      - wordpress
      - database


  proxy:

    image: nginx:latest

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    restart: always

    environment:
      - PING_LISTEN_PORT=3000
    
    ports:
      - 8081:80

    depends_on: 
      - wordpress
    
    networks:
      - app-tier

# Déclaration des volumes nommés
# volumes:

